[package]
name = "krustlet"
version = "0.4.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"
default-run = "krustlet-wascc"
license-file = "LICENSE"
description = "A Kubernetes kubelet implementation in Rust, used for running WebAssembly modules in Kubernetes"
repository = "https://github.com/deislabs/krustlet"
documentation = "https://github.com/deislabs/krustlet/tree/master/docs"
readme = "README.md"
keywords = [
    "wasm",
    "wasi",
    "webassembly",
    "kubernetes",
]
exclude = [
    "docs/*",
    "demos/*",
    ".github/*",
    ".gitignore"
]

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["native-tls"]
native-tls = ["kube/native-tls", "kubelet/kube-native-tls", "wascc-provider/native-tls", "oci-distribution/native-tls"]
rustls-tls = ["kube/rustls-tls", "kubelet/rustls-tls", "wascc-provider/rustls-tls", "oci-distribution/rustls-tls"]

[dependencies]
anyhow = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded", "time"] }
kube = { version= "0.35", default-features = false }
k8s-openapi = { version = "0.8", default-features = false, features = ["v1_17"] }
env_logger = "0.7"
futures = "0.3"
kubelet = { path = "./crates/kubelet", version = "0.4", default-features = false, features = ["cli"] }
wascc-provider = { path = "./crates/wascc-provider", version = "0.4", default-features = false }
wasi-provider = { path = "./crates/wasi-provider", version = "0.4", default-features = false }
oci-distribution = { path = "./crates/oci-distribution", version = "0.3", default-features = false }
dirs = "2.0"
hostname = "0.3"
regex = "1.3"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
reqwest = { version = "0.10", default-features = false }
tempfile = "3.1"

[workspace]
members = [
    "crates/kubelet",
    "crates/oci-distribution",
    "crates/wascc-logging",
    "crates/wascc-provider"
]


[[bin]]
name = "krustlet-wascc"
path = "src/krustlet-wascc.rs"


[[bin]]
name = "krustlet-wasi"
path = "src/krustlet-wasi.rs"

[[bin]]
name = "oneclick"
path = "tests/oneclick/src/main.rs"

[[bin]]
name = "podsmiter"
path = "tests/podsmiter/src/main.rs"
