[package]
name = "kubelet"
version = "0.1.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
dirs = "2.0"
anyhow = "1.0"
futures = { version = "0.3.4", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "0.13.3", default-features = false, features = ["stream"] }
log = "0.4"
reqwest = "0.10.4"
tokio  = { version = "0.2.13", features = ["fs", "stream", "macros"] }
kube = "0.29.0" 
k8s-openapi = { version = "0.7.1", default-features = false, features = ["v1_17"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"], optional = true }
hostname = "^0.3"
native-tls = "0.2.4"
tokio-tls = "0.3.0"
async-stream = "0.2.1"
thiserror = "1.0"
lazy_static = "1.4.0"

[features]
cli = ["clap"]