[package]
name = "oci-distribution"
version = "0.1.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["json", "stream"] }
anyhow = "1.0"
tokio = {version  = "0.2.14", features = ["macros", "fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
www-authenticate = "0.3.0"
hyperx = "0.13"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3.4"